spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/moviedb
    username: moviedb
    password: moviedb

flyway:
  locations: classpath:db/migration, db/init, db/fk
  out-of-order: true

jwt:
  signingKey: secret-key
  expirationInSeconds: 600