server:
  port: ${PORT:8080}
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    active: local

flyway:
  locations: classpath:db/migration, db/init, db/fk
  out-of-order: true

jwt:
  signingKey: secret-key
  expirationInSeconds: 600